### ISSUE TITLE
Doesn't work during playback of recorded video

### ISSUE THREAD

**Issue by jandreaucodes** [jradwan/alexa_tivo_control#3]
Not sure if this is the fault of TiVo, or the app, but it doesn't work during playback.

If you try to send a pause or fast forward command during playback of either a locally recorded show, or one on another TiVo box, the command eventually times out, and the app needs to be restarted. 

This happens both locally and when run through a cloud hosting service.

**Comment by jradwan** [comment]
Sorry I missed this ... never got a notification from GitHub.

First, I'd be interested in what you did to get it working as a hosted service, but that's another discussion.

Second, I thought I had tested this during playback (local or MRS) but will look into it. The telnet interface should still respond during playback (since other remote apps like kmttg or the iOS/Android apps work), so it's probably a bug.

**Comment by jradwan** [comment]
Well, you're right. I thought I had tested during playback of content, but sure enough the commands are received by the server, but the TiVo either doesn't receive them or doesn't process them. I checked my YouTube demo video and it looks like I never did playback there either!

Seems like a major problem for a skill like this. :-) I'll see what I can figure out. 

In my quick testing, it also seems like doing this (during playback) causes the node-app-server crash I logged in issue #1.

**Comment by jradwan** [comment]
After doing a little debugging, it appears that during playback of a recording, the TiVo doesn't send a status message back (like "CH_STATUS 1013 LOCAL" that appears when commands are sent during Live TV). So the commands weren't being sent properly. I believe I've fixed this, and it had the other benefit of fixing issue #1 at the same time.

**Comment by jg123** [comment]
@jradwan You literally fixed this minutes after I first got this error. Thanks!
