### ISSUE TITLE
Alexa response "Im not quite sure how to help with that"

### ISSUE THREAD

**Issue by asantaga** [jradwan/alexa_tivo_control#46]
If i test the tivo control alexa skill from within the skill it works fine, but if I ask the alexa device ask tivo to pause or change channel or anything it simply says "Im not quite sure how to help with that"

any ideas?

**Comment by jradwan** [comment]
How are you invoking the skill? Make sure you start with "Alexa, tell Tivo to ..." and then the command.

So, "Alexa, tell TiVo to pause" or "Alexa, tell TiVo to change to channel 13." Check the skill's log file to make sure it's hearing and parsing correctly.

**Comment by asantaga** [comment]
U used the Alexa tell tivo to pause".. but I think ive sussed it.. I read somewhere today that this can happen if you setup the skill with "US" language as opposed to UK :-)

Im at work now, but I plan to check/test this out later .. I'll let u know! 

Also different question (should probably log a separate ticket for this), how does one "pull" the updated utterances (issue 24)  I tried simply cloning the utternances repo into the alexa-utterances package but it didnt make a difference and the tivo_control package still produced Utterances with + signs.. thanks

**Comment by jradwan** [comment]
Ok, yeah, you might need to do something different with the US vs. UK language. Let me know how it goes.

For issue #24, you can just manually modify the index.js file for the alexa-utterances package with the [code changes](https://github.com/alexa-js/alexa-utterances/pull/24/files) listed in the PR.

**Comment by asantaga** [comment]
Worked!

However there is a whole host of issues we need to solve :-) Ive listed them here but shall I log them as separate issues

1. For UK users you need to make sure the language is English (UK), otherwise the physical alexa simply doesnt recognise the tivo trigger word
2. Multiple SLOT types are not supported in the UK, e.g. AMAZON.GENRE, I simply removed them
3. I still had issues with additional SLOT Types not being accepted and multiple other types
4. For some reason even though i manually pulled issue 24 into alexa_utternces I still got + signs around the optional parameters and the alexa console complained. I simply removed them manually :-) 
5. I  edited the config.json file and disabled all the extra apps (plex,epix,vevo etc) alas when running the alexa tester it still generated all the intents and utterences for these options.. I just editted these out.
6. When changing channel the code would send the number (1.0.6) and then send ENTER. Alas ENTER on the UK virgin tivo basically sends the tivo back to the original channel :-) fixed by commenting out the code which sent [enter]


Do you want me to log these as separate issues?

**Comment by jradwan** [comment]
Glad you got it (sorta) working. You can log those as separate issues if you want, for completeness sake. I'd have to think about how to support the UK Virgin TiVo, maybe a config.json setting that could then be used in the code to accommodate the changes you're referring to.

**Comment by jradwan** [comment]
1. thanks for logging issue #48. I've updated the installation instructions.

2. thanks for logging issue #47. I had no idea so many slot types weren't available outside of the English US language for the skill. You could probably make these custom slots but that would require a good amount of extra work. Sorry! Leaving the language of the skill as English US would allow those slot types to work, but then you run into the problem described above. :( 

3. same as 2.

4. manually replacing the + with the curly braces {} is an acceptable workaround :)

5. if you don't want those app utterances to be generated, you'll need to comment out the intent code blocks in app.js (as you noticed, commenting them out of config.json won't work).

6. The ENTER is only sent during a channel change for the TiVo Mini. Did you maybe have _"mini": true_ in your config.json file? Otherwise the code should be using the SETCH command, which doesn't include the ENTER at the end.

**Comment by jradwan** [comment]
Since you've filed other issues for some of these things, I'm closing this issue.
